### ISSUE TITLE
Which API key is to be used?

### ISSUE THREAD

**Issue by NikitaNeganov** [yandexmobile/react-native-appmetrica#29]
In the application page at `appmetrica.yandex.ru/application/edit?appId=${appId}`
I have 2 API keys - API key for SDK and Post API key.

Which one is to be used with
`AppMetrica.activateWithApiKey`?

Also, is it enough to run the above code once the application is initialized or do I need to include that every time I log an event through AppMetrica?

Thank you

**Comment by NesterovichAlexey** [comment]
Hi.
You need to use API key for SDK.
It is enough to run once after initializing the application

**Comment by NikitaNeganov** [comment]
Great, thanks!
