### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by retyui** [yandexmobile/react-native-appmetrica#41]
I have questions:

- How I can  deidentify user when he\she will sign out?
- How can I do screen tracking for analytics?
> for example firebase has js api for this type of events 
```js
import analytics from '@react-native-firebase/analytics';
// ...
analytics().setCurrentScreen(routeName, routeName);
```

**Comment by dzinad** [comment]
Hello. You should ask our support team (https://clck.ru/JGnCX) this question.
