### ISSUE TITLE
TypeError: _reactNativeAppmetrica.default.activateWithConfig is not a function.

### ISSUE THREAD

**Issue by Preeternal** [yandexmobile/react-native-appmetrica#48]
I got an error 
```
TypeError: _reactNativeAppmetrica.default.activateWithConfig is not a function. (In '_reactNativeAppmetrica.default.activateWithConfig({
    apiKey: 'myIpKey',
    sessionTimeout: 120,
    firstActivationAsUpdate: true
  })', '_reactNativeAppmetrica.default.activateWithConfig' is undefined)
```
Could you please to change readme? There is no default export in the code for activateWithConfig, but there is activate function:
<img width="304" alt="изображение" src="https://user-images.githubusercontent.com/24249735/102818787-04a8c400-43db-11eb-809f-d3f1b33fd662.png">

So correct description in README.MD should be:

```
AppMetrica.activate({
  apiKey: '...KEY...',
  sessionTimeout: 120,
  firstActivationAsUpdate: true,
});
```

**Comment by NesterovichAlexey** [comment]
Thank you! The file is correct now.

**Comment by plus24-library** [comment]
TypeError: _reactNativeAppmetrica.default.activate is not a function. (In '_reactNativeAppmetrica.default.activate({
      apiKey: '...KEY...',
      sessionTimeout: 120,
      firstActivationAsUpdate: true
    })', '_reactNativeAppmetrica.default.activate' is undefined)

**Comment by AppMetricaOvermindGenius180iq** [comment]
Добрый день!Ваше письмо получено и зарегистрировано под уникальным номером № 12485195. Ответ обязательно будет предоставлен, пожалуйста, ожидайте.Просим Вас не отправлять повторное письмо по данному вопросу - оно будет считаться новой заявкой и может быть обработано позднее.Помощь сервиса: https://yandex.ru/support/direct/?from=email--С уважением,Отдел клиентского сервисател.: 8 800 234-24-80 (звонок из регионов России бесплатный)тел.: +7 495 739-37-77&nbsp01.04.2021, 09:48, "plus24-library" ***@***.***>:
TypeError: _reactNativeAppmetrica.default.activate is not a function. (In '_reactNativeAppmetrica.default.activate({
apiKey: '...KEY...',
sessionTimeout: 120,
firstActivationAsUpdate: true
})', '_reactNativeAppmetrica.default.activate' is undefined)
